# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - uses: jorelali/setup-elm@v3
      with:
        elm-version: 0.19.1
    - working-directory: ./
      name: Complie and generate code
      run: mvn -U clean compile
    - working-directory: ./elm
      name: Build Elm app
      run: elm make src/Main.elm --output=web/main.js
    - working-directory: ./
      name: Build with Maven
      run: mvn -B package --file pom.xml
